<?php

use Drupal\node\Entity\Node;

function my_module_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
    if ($entity->bundle() !== 'courses') {
        return;
    }
    $config = \Drupal::config('my_module.settings');
  $organization_name = $config->get('organization_name');
    # If the variable is not set/config name is wrong -> we return nothing and exit the hook
    if (!$organization_name) {
        return;
    }
    $node = Node::load($entity->id());
    $node->set('field_organization', $organization_name);
    $$node->save();
}
